close all; clear all;% clc
%% Solver & Algorithm list
order = ["Ray", "D4", "Ray_match"];
diff_method = ["Schimd", "Trefethen"];
constructAB_method = ["D4", "Schimd"];
solveGEPmethod = ["qr", "qz", "eig", "eigs", "polyeig", "singgep", "jdqz"];
%% Inputs
solver = [3,1,1]; % [order, diff_method, constructAB_method]
algorithm = 1; % solveGEPmethod
do_balancing = 'n';
N = 400;
k = 0.5;
Re = inf;
Fr2 = 2.25;
h = @(k) 2*pi/k;
% h = @(k) 6;
zL = 0.74708299;
%% Set solver
method = [order(solver(1)), diff_method(solver(2)), constructAB_method(solver(3))];
alg = solveGEPmethod(algorithm);
%% Run solver
[o, an, cA, errGEP, db, z, phi, zc, zLo] = wZhang_solver2(N,k,h(k),Re,Fr2,method,alg,do_balancing,zL,'y');
%% Plot
figure('position',[0 0 1680 960]);
subplot(1,4,1);
plot(abs(phi(:,1)),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
set(gca,'fontsize',20);
if (h(k) > 6)
    blim = -6;
else
    blim = fix(-h(k));
end
xlabel('$||\phi||$','FontSize',30, 'Interpreter', 'LaTeX');
ylabel('$z$','FontSize',30, 'Interpreter', 'LaTeX');
ylim([blim 0]);
% yax = sort([fix(-h(k)):0.5:0 -zL]); 
% yticks(yax);
% ax = gca;
% ax.YTickLabel{yax == -zL} = ['\color{red}' ax.YTickLabel{yax == -zL}];
grid on;
subplot(1,4,2);
plot(unwrap(angle(phi(:,1))),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
set(gca,'fontsize',20);
ylim([blim 0]);
xlabel('$angle(\phi)$','FontSize',30, 'Interpreter', 'LaTeX');
grid on;
subplot(1,4,3);
plot(abs(phi(:,2)),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
set(gca,'fontsize',20);
ylim([blim 0]);
xlabel('$||\frac{d \phi }{dz}||$','FontSize',30, 'Interpreter', 'LaTeX');
% yticks(yax);
% ax = gca;
% ax.YTickLabel{yax == -zL} = ['\color{red}' ax.YTickLabel{yax == -zL}];
grid on;
subplot(1,4,4);
plot(abs(phi(:,3)),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
set(gca,'fontsize',20);
xlabel('$||\frac{d^2 \phi }{dz^2}||$','FontSize',30, 'Interpreter', 'LaTeX');
ylim([blim 0]);
grid on;
%% d2
figure('position',[0 0 1680 960]);
subplot(1,4,1);
plot(abs(phi(:,3)),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
set(gca,'fontsize',20);
xlabel('$||\frac{d^2 \phi }{dz^2}||$','FontSize',30, 'Interpreter', 'LaTeX');
ylabel('$z$','FontSize',30, 'Interpreter', 'LaTeX', 'rotation', 0, 'HorizontalAlignment','right');
ylim([blim 0]);
grid on;
subplot(1,4,2);
plot(unwrap(angle(phi(:,3))),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
set(gca,'fontsize',20);
xlabel('$angle(\frac{d^2 \phi }{dz^2})$','FontSize',30, 'Interpreter', 'LaTeX');
ylim([blim 0]);
xticks(-pi:0.5*pi:0.5*pi);
% xlim([-pi 2]);
set(gca,'XTickLabel',{'-\pi','-0.5\pi','0','0.5\pi'});
grid on;
subplot(1,4,3);
plot(real(phi(:,3)),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
xlabel('$real(\frac{d^2 \phi }{dz^2})$','FontSize',30, 'Interpreter', 'LaTeX');
set(gca,'fontsize',20);
ylim([blim 0]);
grid on;
subplot(1,4,4);
plot(imag(phi(:,3)),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
xlabel('$imag(\frac{d^2 \phi }{dz^2})$','FontSize',30, 'Interpreter', 'LaTeX');
set(gca,'fontsize',20);
ylim([blim 0]);
grid on;
%% D1
figure('position',[0 0 1680 960]);
subplot(1,4,1);
plot(abs(phi(:,2)),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
set(gca,'fontsize',20);
xlabel('$||\frac{d\phi }{dz}||$','FontSize',30, 'Interpreter', 'LaTeX');
ylabel('$z$','FontSize',30, 'Interpreter', 'LaTeX', 'rotation', 0, 'HorizontalAlignment','right');
ylim([blim 0]);
grid on;
subplot(1,4,2);
plot(unwrap(angle(phi(:,2))),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
set(gca,'fontsize',20);
xlabel('$angle(\frac{d \phi }{dz})$','FontSize',30, 'Interpreter', 'LaTeX');
ylim([blim 0]);
xticks(-pi:0.5*pi:0.5*pi);
% xlim([-pi 2]);
set(gca,'XTickLabel',{'-\pi','-0.5\pi','0','0.5\pi'});
grid on;
subplot(1,4,3);
plot(real(phi(:,2)),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
xlabel('$real(\frac{d \phi }{dz})$','FontSize',30, 'Interpreter', 'LaTeX');
set(gca,'fontsize',20);
ylim([blim 0]);
grid on;
subplot(1,4,4);
plot(imag(phi(:,2)),z,'-k.','linewidth',1,'markersize',10);
hold on;
yline(zc, '-.r', 'linewidth', 1.5);
yline(-zL, '--b', 'linewidth', 1.5);
hold off;
xlabel('$imag(\frac{d \phi }{dz})$','FontSize',30, 'Interpreter', 'LaTeX');
set(gca,'fontsize',20);
ylim([blim 0]);
grid on;